name = "scope/scope"
version = "0.1.0"
license = "MIT"

[target]
environment = "roblox"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[indices]
default = "https://github.com/pesde-pkg/index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.2.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.5.1", target = "lune" }
UiLabs = { wally = "pepeeltoro41/ui-labs", version = "^2.4.2" }

[engines]
pesde = "^0.7.0"
lune = "^0.10.2"

[dependencies]
Janitor = { wally = "howmanysmall/janitor", version = "^1.18.3" }
Packet = { wally = "sjdinsd/packet", version = "^0.1.91" }
Framework = { wally = "yuzkkj/framework", version = "^1.0.3" }
Promise = { wally = "howmanysmall/typed-promise", version = "^4.0.6" }
PlayerDataManager = { wally = "yuzkkj/player-data-manager", version = "^0.4.7" }
Signal = { wally = "stravant/goodsignal", version = "^0.3.1" }
Conch-Ui = { wally = "alicesaidhi/conch-ui", version = "^0.3.1" }
Conch = { wally = "alicesaidhi/conch", version = "^0.3.1" }
